# -*- coding: utf-8 -*-
"""preprocess-all-modes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R-fl6VLDuneQMMovEAemB3odW4VNkuCJ

## Video Sentiment Analysis in the Wild
### Ensembling Notebook | CS231n

This notebook preprocesses input videos to extract faces, frames, poses, and audio before running pre-trained models for each modality to predict group sentiment (positive, negative, or neutral).
"""

"""#### Pre-Processing

Here, we will instantiate each of the preprocessors and process all of the input video files.

NOTE: Change the input parameters as needed.

WARNING: This may take several hours to complete, depending on the number of files.

In general, pre-processing will extract the following:
- Video frames
- Pose keypoints
- Faces from each video frame
- Audio waveform and audio features
"""

from src.preprocessors.scene_preprocessor import VideoPreprocessor
from src.preprocessors.face_preprocessor import FacePreprocessor
from src.preprocessors.pose_preprocessor import PosePreprocessor
from src.preprocessors.audio_preprocessor import AudioPreprocessor


def preprocess(video_folder="train-tiny.zip", label_file="Train_labels.txt", local_base_path="train-tiny"):
    video_preprocessor = VideoPreprocessor(
        video_folder=video_folder,
        label_file=label_file,
        output_folder=f"{local_base_path}-local",
        output_file=f"{local_base_path}-local.zip"
    )

    face_preprocessor = FacePreprocessor(
        video_folder=video_folder,
        output_folder=f"{local_base_path}-faces",
        output_file=f"{local_base_path}-faces.zip"
    )

    pose_preprocessor = PosePreprocessor(
        video_frame_folder=f"{local_base_path}-local",
        output_folder=f"{local_base_path}-pose",
        output_file=f"{local_base_path}-pose.zip"
    )

    audio_preprocessor = AudioPreprocessor(
        video_folder=video_folder,
        label_path=label_file,
        output_folder=f"{local_base_path}-audio",
        output_file=f"{local_base_path}-audio.zip"
    )

    preprocessors_list = [video_preprocessor, face_preprocessor, pose_preprocessor, audio_preprocessor , audio_preprocessor_val]

    for preprocessor in preprocessors_list:
        preprocessor.preprocess()
